version: "3.3"

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    django:
        build:
            context: .
            dockerfile: docker/Dockerfile
        # command: python -c "import time; time.sleep(1000)"
        environment:
            - DEBUG=${DEBUG}
            - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
            - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432

        volumes:
            - ./src:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
